# Taken from obytes' react native template: https://github.com/obytes/react-native-template-obytes

name: Precheck

on:
  pull_request:
    branches: [main]
  workflow_call:

jobs:
  install:
    name: Prepare enviroment + Cache
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¦ Checkout project repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ğŸ“¦ Setup Node + PNPM + install deps
        uses: ./.github/actions/setup-node-pnpm-install

  lint:
    name: Lint TS (eslint, prettier)
    needs: [install]
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¦ Checkout project repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ğŸ“¦ Setup Node + PNPM + install deps
        uses: ./.github/actions/setup-node-pnpm-install

      - name: ğŸƒâ€â™‚ï¸ Run ESLint PR
        if: github.event_name == 'pull_request'
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          eslint_flags: 'src --max-warnings=0'

      - name: ğŸƒâ€â™‚ï¸ Run ESLint PR
        if: github.event_name != 'pull_request'
        run: pnpm run lint

  type-check:
    name: Type Check (tsc)
    needs: [install]
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¦ Checkout project repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ğŸ“¦ Setup Node + PNPM + install deps
        uses: ./.github/actions/setup-node-pnpm-install

      - name: ğŸ“¦ Install Reviewdog
        if: github.event_name == 'pull_request'
        uses: reviewdog/action-setup@v1

      - name: ğŸƒâ€â™‚ï¸ Run TypeScript PR # Reviewdog tsc errorformat: %f:%l:%c - error TS%n: %m
        # We only need to add the reviewdog step if it's a pull request
        if: github.event_name == 'pull_request'
        run: |
          pnpm type-check | reviewdog -name="tsc" -efm="%f(%l,%c): error TS%n: %m" -reporter="github-pr-review" -filter-mode="nofilter" -fail-on-error -tee
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name:
          ğŸƒâ€â™‚ï¸ Run TypeScript Commit
          # If it's not a Pull Request then we just need to run the type-check
        if: github.event_name != 'pull_request'
        run: pnpm type-check
